# Generated by Django 4.2.6 on 2023-11-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Available'), (2, 'Unavailable')]),
        ),
        migrations.CreateModel(
            name='Shuffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_shuffle', models.DateTimeField()),
                ('next_shuffle', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Started'), (1, 'In Progress'), (2, 'Complete')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curator.concept')),
            ],
        ),
    ]
