# Generated by Django 4.2.6 on 2023-11-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0002_alter_application_status_shuffle'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='slug',
            field=models.SlugField(max_length=75, null=True),
        ),
    ]
