# Generated by Django 4.2.6 on 2023-12-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0003_concept_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='curator',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
