# Generated by Django 4.2.6 on 2024-02-13 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0013_remove_opportunity_invite_status_and_more'),
        ('curator', '0006_shuffle_type_alter_shuffle_status_delete_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuffle',
            name='chosen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.artist'),
        ),
        migrations.AddField(
            model_name='shuffle',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='shuffle',
            name='retries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shuffle',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shuffle',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Started'), (1, 'In Progress'), (2, 'Invite Sent'), (3, 'Accepted'), (4, 'Reshuffle'), (5, 'Complete')], default=0),
        ),
    ]
