# Generated by Django 4.2.6 on 2024-02-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0008_organization_curator_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shuffle',
            old_name='end_date',
            new_name='closed_at',
        ),
        migrations.RemoveField(
            model_name='curator',
            name='slug',
        ),
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
