# Generated by Django 4.2.6 on 2024-02-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0009_rename_end_date_shuffle_closed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuffle',
            name='last_shuffle',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shuffle',
            name='next_shuffle',
            field=models.DateTimeField(null=True),
        ),
    ]
