# Generated by Django 4.2.6 on 2024-02-20 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0010_alter_shuffle_last_shuffle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='concept_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='curator',
            name='curator_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='shuffle',
            name='shuffle_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
