# Generated by Django 4.2.6 on 2024-02-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0011_concept_concept_id_curator_curator_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shuffle',
            name='last_shuffle',
        ),
        migrations.RemoveField(
            model_name='shuffle',
            name='next_shuffle',
        ),
        migrations.AddField(
            model_name='organization',
            name='last_shuffle',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='next_shuffle',
            field=models.DateTimeField(null=True),
        ),
    ]
