# Generated by Django 4.2.6 on 2024-02-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0012_remove_shuffle_last_shuffle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
