# Generated by Django 4.2.6 on 2024-02-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0013_concept_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuffle',
            name='previous_shuffle_id',
            field=models.UUIDField(null=True),
        ),
    ]
