# Generated by Django 4.2.6 on 2024-02-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0014_shuffle_previous_shuffle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shuffle',
            name='type',
        ),
    ]
