# Generated by Django 4.2.6 on 2024-02-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0015_remove_shuffle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuffle',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Started'), (1, 'In Progress'), (2, 'Invite Sent'), (3, 'Accepted'), (4, 'Reshuffle'), (5, 'Complete'), (6, 'Failed')], default=0),
        ),
    ]
