# Generated by Django 4.2.6 on 2024-02-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0017_remove_concept_poster_alter_curator_curator_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concept',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='concept',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='concept',
            name='recurrence_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Daily'), (1, 'Weekly'), (2, 'Monthly')], null=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='times_per_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='times_per_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
