# Generated by Django 4.2.6 on 2024-02-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0021_concept_day_of_week_concept_end_concept_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concept',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='concept',
            old_name='start',
            new_name='start_time',
        ),
        migrations.AlterField(
            model_name='concept',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
