# Generated by Django 4.2.6 on 2024-02-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0022_rename_end_concept_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuffle',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Invite Sent'), (3, 'Accepted'), (4, 'Reshuffle'), (5, 'Complete'), (6, 'Failed')], default=0),
        ),
    ]
