# Generated by Django 4.2.6 on 2024-02-29 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0028_alter_opportunity_event'),
        ('curator', '0023_alter_shuffle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuffle',
            name='pick',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.subscriber'),
        ),
    ]
