# Generated by Django 4.2.6 on 2024-02-29 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0024_alter_shuffle_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='reshuffle_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='shuffle_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curator',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curators', related_query_name='curator', to='curator.organization'),
        ),
        migrations.AlterField(
            model_name='shuffle',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Invite Sent'), (3, 'Reshuffle'), (4, 'Complete'), (5, 'Failed')], default=0),
        ),
    ]
