# Generated by Django 4.2.6 on 2024-03-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0025_concept_reshuffle_count_concept_shuffle_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='reshuffle_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='concept',
            name='shuffle_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
