# Generated by Django 4.2.6 on 2024-03-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0026_alter_concept_reshuffle_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuffle',
            name='previous_shuffle_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
