# Generated by Django 4.2.6 on 2024-03-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0027_alter_shuffle_previous_shuffle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
