# Generated by Django 4.2.6 on 2024-03-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0028_alter_concept_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='curator',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
