# Generated by Django 4.2.6 on 2024-03-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0029_curator_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shuffle',
            name='previous_shuffle_id',
        ),
    ]
