# Generated by Django 4.2.6 on 2024-03-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0030_remove_shuffle_previous_shuffle_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('json', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'system_config',
            },
        ),
    ]
