# Generated by Django 4.2.6 on 2024-03-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0031_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='name',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='json',
            new_name='value',
        ),
        migrations.AddField(
            model_name='config',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Africas Talking SMS')], default=0),
        ),
    ]
