# Generated by Django 4.2.6 on 2024-03-02 23:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0032_rename_name_config_key_rename_json_config_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='config_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
