# Generated by Django 4.2.6 on 2024-03-02 23:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0033_config_config_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='config_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
