# Generated by Django 4.2.6 on 2024-03-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0035_organization_website_alter_shuffle_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='end_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Never'), (1, 'After N Occurrences'), (2, 'End Date')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
    ]
