# Generated by Django 4.2.6 on 2024-03-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0036_concept_end_date_concept_end_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Africas Talking SMS'), (1, 'Activepieces Webhook')], default=0),
        ),
    ]
