# Generated by Django 4.2.6 on 2024-03-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0038_alter_config_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'JSON Config'), (1, 'Activepieces Webhook'), (2, 'SMS Template')], default=0),
        ),
    ]
