# Generated by Django 4.2.6 on 2024-03-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0039_alter_config_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
