# Generated by Django 4.2.6 on 2024-03-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0040_alter_config_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.TextField(),
        ),
    ]
