# Generated by Django 4.2.6 on 2024-03-06 10:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0041_alter_config_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuffle',
            name='shuffle_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
