# Generated by Django 4.2.6 on 2024-02-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0002_remove_event_opportunity_event_artist_event_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='event',
            name='concept',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Never'), (1, 'After N Occurrences'), (2, 'End Date')], null=True),
        ),
    ]
