# Generated by Django 4.2.6 on 2024-02-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0005_remove_event_description_remove_event_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Successful'), (2, 'Cancelled'), (3, 'Rescheduled'), (4, 'Failed')], null=True),
        ),
    ]
