# Generated by Django 4.2.6 on 2024-03-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0006_event_title_alter_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
    ]
