# Generated by Django 4.2.6 on 2024-03-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0007_remove_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='closed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Successful'), (2, 'Cancelled'), (3, 'Rescheduled')], null=True),
        ),
    ]
