# Generated by Django 4.2.6 on 2023-10-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('bio', models.CharField(max_length=320)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='artist-photos/')),
                ('instagram', models.URLField(unique=True)),
                ('opportunity_status', models.CharField(choices=[('WAITING', 'Waiting'), ('PERFORMED', 'Performed'), ('NEXT_CYCLE', 'Next Cycle')], max_length=15)),
                ('invite_status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Accepted'), ('UNAVAILABLE', 'Unavailable')], max_length=15)),
                ('country', models.CharField(max_length=3)),
                ('performance_count', models.PositiveSmallIntegerField(default=0)),
                ('next_performance', models.DateTimeField(null=True)),
                ('last_performance', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'artist_profile',
            },
        ),
    ]
