# Generated by Django 4.2.6 on 2023-10-22 06:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=models.CharField(default='KEN', max_length=3),
        ),
    ]
