# Generated by Django 4.2.6 on 2023-10-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_alter_artist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.URLField(help_text='Link to online photo'),
        ),
    ]
