# Generated by Django 4.2.6 on 2023-10-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_alter_artist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='invite_status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Accepted'), ('UNAVAILABLE', 'Unavailable')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='opportunity_status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('PERFORMED', 'Performed'), ('NEXT_CYCLE', 'Next Cycle')], max_length=15, null=True),
        ),
    ]
