# Generated by Django 4.2.6 on 2023-10-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_alter_artist_invite_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='mailerlite_subscriber_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
