# Generated by Django 4.2.6 on 2023-10-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_artist_mailerlite_subscriber_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='mailerlite_subscriber_group_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
