# Generated by Django 4.2.6 on 2023-11-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_artist_mailerlite_subscriber_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='opportunity_status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('PERFORMED', 'Performed'), ('NEXT_CYCLE', 'Next Cycle')], default='WAITING', max_length=15),
        ),
    ]
