# Generated by Django 4.2.6 on 2023-11-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_alter_artist_opportunity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='invite_status',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Accepted'), ('UNAVAILABLE', 'Unavailable')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_performance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='mailerlite_subscriber_group_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='mailerlite_subscriber_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='next_performance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.URLField(blank=True, help_text='Link to online photo', null=True),
        ),
    ]
