# Generated by Django 4.2.6 on 2023-11-12 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0009_alter_artist_instagram_alter_artist_invite_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='artist',
            name='opportunity_status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('NEXT', 'Next'), ('PERFORMED', 'Performed'), ('NEXT_CYCLE', 'Next Cycle')], default='WAITING', max_length=15),
        ),
    ]
