# Generated by Django 4.2.6 on 2024-02-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0013_remove_opportunity_invite_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='acceptance_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='expired_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='mixcloud',
            field=models.URLField(blank=True, help_text='Link to mixcloud', null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='skip_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='soundcloud',
            field=models.URLField(blank=True, help_text='Link to soundcloud', null=True),
        ),
    ]
