# Generated by Django 4.2.6 on 2024-02-20 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0015_artist_epk_artist_is_active_alter_opportunity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='opportunity_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
