# Generated by Django 4.2.6 on 2024-02-20 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0016_opportunity_opportunity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='invite_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'New'), (1, 'Waiting Acceptance'), (2, 'Accepted'), (3, 'Skip'), (4, 'Expired')], null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', related_query_name='opportunities', to='artist.artist'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Potential'), (1, 'Next Performing'), (2, 'Performed')], default=0, null=True),
        ),
    ]
