# Generated by Django 4.2.6 on 2024-02-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0017_opportunity_invite_status_alter_opportunity_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='invite_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'New'), (1, 'Sent'), (2, 'Awaiting Acceptance'), (3, 'Accepted'), (4, 'Skip'), (5, 'Expired')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Potential'), (1, 'Next Performing'), (2, 'Performed'), (3, 'Next Cycle')], default=0, null=True),
        ),
    ]
