# Generated by Django 4.2.6 on 2024-02-23 08:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0012_remove_shuffle_last_shuffle_and_more'),
        ('artist', '0018_alter_opportunity_invite_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='acceptance_count',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='expired_count',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='last_performance',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='next_performance',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='performance_count',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='selection_count',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='skip_count',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='concept',
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_id', models.UUIDField(default=uuid.uuid4)),
                ('selection_count', models.PositiveSmallIntegerField(default=0)),
                ('acceptance_count', models.PositiveSmallIntegerField(default=0)),
                ('expired_count', models.PositiveSmallIntegerField(default=0)),
                ('skip_count', models.PositiveSmallIntegerField(default=0)),
                ('performance_count', models.PositiveSmallIntegerField(default=0)),
                ('next_performance', models.DateTimeField(blank=True, null=True)),
                ('last_performance', models.DateTimeField(blank=True, null=True)),
                ('is_subscribed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', related_query_name='opportunities', to='artist.artist')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='curator.concept')),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='subscriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.subscriber'),
        ),
    ]
