# Generated by Django 4.2.6 on 2024-02-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0020_alter_subscriber_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name_plural': 'Subscribers'},
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='invite_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Sent'), (2, 'Awaiting Acceptance'), (3, 'Accepted'), (4, 'Skip'), (5, 'Expired')], default=0, null=True),
        ),
    ]
