# Generated by Django 4.2.6 on 2024-02-24 16:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0021_alter_opportunity_options_alter_subscriber_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='outcome_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Sent'), (2, 'Cancelled'), (3, 'Postponed')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='previous_opportunity_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
