# Generated by Django 4.2.6 on 2024-02-27 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0017_remove_concept_poster_alter_curator_curator_id_and_more'),
        ('artist', '0024_opportunity_invite_sent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='outcome_status',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', related_query_name='subscription', to='artist.artist'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_subscriptions', related_query_name='concept_subscription', to='curator.concept'),
        ),
    ]
