# Generated by Django 4.2.6 on 2024-02-28 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0025_remove_opportunity_outcome_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='invite_closed_at',
            new_name='closed_at',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='invite_sent_at',
            new_name='sent_at',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='opportunity_closed_at',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='status',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Potential'), (1, 'Next Performing'), (2, 'Performed'), (3, 'Next Cycle')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='invite_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Awaiting Acceptance'), (2, 'Accepted'), (3, 'Skipped'), (4, 'Expired')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='subscriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', related_query_name='opportunity', to='artist.subscriber'),
        ),
    ]
