# Generated by Django 4.2.6 on 2024-02-29 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0006_event_title_alter_event_status'),
        ('artist', '0027_rename_invite_status_opportunity_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concept_opportunities', related_query_name='concept_opportunity', to='calendar.event'),
        ),
    ]
