# Generated by Django 4.2.6 on 2024-02-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0028_alter_opportunity_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='shuffle_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
