# Generated by Django 4.2.6 on 2024-03-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0029_opportunity_shuffle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='notes_to_curator',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='reject_reason',
            field=models.PositiveSmallIntegerField(choices=[(0, '------'), (1, 'Pending'), (2, 'Reschedule'), (3, 'Busy'), (4, 'Pass')], default=0, null=True),
        ),
    ]
