# Generated by Django 4.2.6 on 2024-03-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0030_opportunity_notes_to_curator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='reject_reason',
            field=models.PositiveSmallIntegerField(choices=[(0, '------'), (1, 'Pending'), (2, 'Reschedule'), (3, 'Busy'), (4, 'Pass')], null=True),
        ),
    ]
