# Generated by Django 4.2.6 on 2024-03-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0031_alter_opportunity_reject_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='reject_reason',
            field=models.PositiveSmallIntegerField(choices=[(0, '------'), (1, 'Unavailable'), (2, 'Reschedule'), (3, 'Pass')], null=True),
        ),
    ]
