# Generated by Django 4.2.6 on 2024-03-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0033_alter_opportunity_shuffle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='sms_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
