# Generated by Django 4.2.6 on 2024-03-06 14:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0034_subscriber_sms_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Potential'), (2, 'Next Up'), (3, 'Next Performing'), (4, 'Performed'), (5, 'Next Cycle')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscriber_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
