# Generated by Django 4.2.6 on 2024-03-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0035_alter_artist_artist_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='notes_to_curator',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
