# Generated by Django 4.2.6 on 2023-10-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=150)),
                ('website_url', models.URLField(unique=True)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=150)),
                ('tags', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=250)),
                ('meta_description', models.CharField(max_length=100, null=True)),
                ('meta_keywords', models.CharField(max_length=100, null=True)),
                ('meta_filter', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'wordpress_site',
            },
        ),
    ]
