# Generated by Django 4.2.6 on 2023-10-27 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0002_alter_site_content_alter_site_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='content',
        ),
        migrations.RemoveField(
            model_name='site',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='site',
            name='meta_filter',
        ),
        migrations.RemoveField(
            model_name='site',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='site',
            name='status',
        ),
        migrations.RemoveField(
            model_name='site',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='site',
            name='title',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=250)),
                ('meta_description', models.CharField(max_length=100)),
                ('meta_keywords', models.CharField(max_length=100)),
                ('meta_filter', models.CharField(max_length=100)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wordpress.site')),
            ],
            options={
                'db_table': 'wordpress_post',
            },
        ),
    ]
