# Generated by Django 4.2.6 on 2023-10-29 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0006_post_image_alt_text_post_image_caption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='wp_site_id',
            new_name='site_id',
        ),
    ]
