# Generated by Django 4.2.6 on 2023-10-29 05:11

from django.db import migrations, models
import shuffle.wordpress.models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0007_rename_wp_site_id_site_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.CharField(default=shuffle.wordpress.models.alpha, max_length=32),
        ),
    ]
