# Generated by Django 4.2.6 on 2023-10-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0009_remove_post_content_remove_post_meta_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=150, null=True),
        ),
    ]
