# Generated by Django 4.2.6 on 2023-10-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0010_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_alt_text',
            new_name='media_alt_text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image_caption',
            new_name='media_caption',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image_description',
            new_name='media_description',
        ),
    ]
