# Generated by Django 4.2.6 on 2023-10-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0012_alter_post_media_alt_text_alter_post_media_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_alt_text',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_caption',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
