# Generated by Django 4.2.6 on 2023-11-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0013_alter_post_media_alt_text_alter_post_media_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='business_address_locality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='business_address_region',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='business_country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='business_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='business_phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='business_postal_code',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='business_street_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
