# Generated by Django 4.2.6 on 2023-11-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpress', '0014_site_business_address_locality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='business_address_locality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='business_address_region',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='business_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='business_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='business_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='business_postal_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='business_street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
